### ISSUE TITLE
Support Angular 17 in ngx-miniprofiler

### ISSUE THREAD

**Issue by edvinkuric** [hickorytechnology/ngx-miniprofiler#2]
Hello,

First, I want to express my gratitude for the ngx-miniprofiler repository; it's been working wonderfully for us! 😊

We've encountered an issue related to the supported Angular versions. Currently, ngx-miniprofiler supports Angular versions 14 to 16. As our projects works with Angular 17, we are keen to continue using this excellent tool with the latest Angular version without any additional "hacks" like the --force option.

Could you please consider updating the ngx-miniprofiler to support Angular 17? This update would be incredibly beneficial for our development environment since we currently have build problems with using the "--legacy-peer-deps" as well.

Thank you for considering this request. Looking forward to your response!

Best regards,
Edvin

**Comment by jpsullivan** [comment]
Hey @edvinkuric, thanks for the kind words! I'd be happy to bump the version requirements on this -- I'll need to test for breaking changes beforehand, but I'll try to get this done by the end of the week.

**Comment by jpsullivan** [comment]
Hey again @edvinkuric! Sorry about the delay but I was finally able to test and release v1.0.4 of the library which includes Angular 17 support. Feel free to let me know if you experience any issues and I'll be happy to sort them out.
